import { L10n } from '@syncfusion/ej2-base';

L10n.load({
    'sr': {
        schedule: {
            saveButton: 'Rezerviši',
            cancelButton: 'Odustani',
            deleteButton: 'Izbriši',
            newEvent: 'Novi termin',
            editEvent: 'Izmeni termin',
            today: 'Danas',
            day: 'Dan',
            week: 'Nedelja',
            workWeek: 'Radna Nedelja',
            agenda: 'Dnevni red',
            month: 'Mesec',
            allDay: 'Ceo dan',
            timelineDay: 'Vremenska linija Dana',
            timelineWeek: 'Vremenska linija Nedelje',
            timelineWorkWeek: 'Vremenska linija Radne Nedelje',
            timelineMonth: 'Vremenska linija Meseca',
            noEvents: 'Nema događaja',
            emptyContainer: 'Nema zakazanih termina',
            start: 'Početak',
            end: 'Kraj',
            more: 'više',
            close: 'Zatvori',
            cancel: 'Otkaži',
            delete: 'Izbriši',
            title: 'Naslov',
            subject: 'Tema',
            location: 'Lokacija',
            description: 'Opis',
            timezone: 'Vremenska zona',
            allDay: 'Ceo dan',
            startTime: 'Vreme početka',
            endTime: 'Vreme završetka',
            recurrence: 'Ponavljanje',
            recurrenceRule: 'Pravilo ponavljanja',
            none: 'Nema',
            daily: 'Dnevno',
            weekly: 'Nedeljno',
            monthly: 'Mesečno',
            yearly: 'Godišnje',
            never: 'Nikad',
            until: 'Do',
            count: 'Broj ponavljanja',
            first: 'Prvi',
            second: 'Drugi',
            third: 'Treći',
            fourth: 'Četvrti',
            last: 'Poslednji',
            repeat: 'Ponovi',
            repeatEvery: 'Ponovi svaki',
            weeks: 'Nedelje',
            months: 'Meseci',
            years: 'Godine',
            on: 'Na',
            endAfter: 'Završi posle',
            summary: 'Rezime',
            occurrences: 'Ponavljanja',
            dailyInterval: 'dana',
            weeklyInterval: 'nedelja',
            monthlyInterval: 'meseci',
            yearlyInterval: 'godina',
            allDayEvent: 'Celodnevni događaj',
            label: 'Oznaka',
            busy: 'Zauzeto',
            free: 'Slobodno',
            starts: 'Počinje',
            ends: 'Završava',
            edit: 'Izmeni',
            create: 'Kreiraj',
            editEvent: 'Izmeni događaj',
            eventName: 'Naziv događaja',
            eventDetails: 'Detalji događaja',
            event: 'Događaj',
            add: 'Dodaj',
            ok: 'U redu',
            recurrenceAlert: 'Upozorenje o ponavljanju',
            validationError: 'Greška u validaciji',
            deleteEvent: 'Izbriši događaj',
            editEvent: 'Izmeni događaj',
            deleteMultipleEvents: 'Izbriši više događaja',
            deleteRecurrenceEvent: 'Izbriši ponavljajući događaj',
            deleteOccurrence: 'Izbriši pojavu',
            update: 'Ažuriraj',
            startEndError: 'Vreme završetka mora biti veće od vremena početka',
            endError: 'Vreme završetka mora biti veće od vremena početka',
            sameDayError: 'Događaj ne može biti celodnevni i imati vremenske oznake',
            occurrence: 'Pojava',
            series: 'Serija',
            reminder: 'Podsetnik',
            noTitle: 'Bez naslova',
            category: 'Kategorija',
            privateEvent: 'Privatan događaj',
            groupEvent: 'Grupni događaj',
            publicEvent: 'Javni događaj',
            room: 'Soba',
            location: 'Lokacija',
            allDay: 'Ceo dan',
            owner: 'Vlasnik',
            attendees: 'Učesnici',
            repeat: 'Ponovi',
            repeatEvent: 'Ponavljajući događaj',
            repeatAction: 'Akcija ponavljanja',
            week: 'Nedelja',
            workWeek: 'Radna Nedelja',
            month: 'Mesec',
            agenda: 'Dnevni red',
            timelineDay: 'Vremenska linija Dana',
            timelineWeek: 'Vremenska linija Nedelje',
            timelineWorkWeek: 'Vremenska linija Radne Nedelje',
            timelineMonth: 'Vremenska linija Meseca',
            day: 'Dan',
            week: 'Nedelja',
            workWeek: 'Radna Nedelja',
            month: 'Mesec',
            year: 'Godina',
            agenda: 'Dnevni red',
            timelineDay: 'Vremenska linija Dana',
            timelineWeek: 'Vremenska linija Nedelje',
            timelineWorkWeek: 'Vremenska linija Radne Nedelje',
            timelineMonth: 'Vremenska linija Meseca',
            more: 'više',
            less: 'manje'
        }
    }
});
